apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  selector:
    matchLabels:
      app: nodejs
      tier: backend
      track: stable
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nodejs
        tier: backend
        track: stable
    spec:
      containers:
      - name: nodejs
        image: build/ubuntu-nodejs:1.0.0
        ports:
        - containerPort: 1233
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 1233
      targetPort: 1233
  